### PR TITLE
Fix errors when filenames contains spaces.

### PR DESCRIPTION
**Pull request by 0x3333**
Fix issue #14 .

### CODE REVIEW

**Comment by wubzz** [comment]
Thanks! Published.

**Comment by wubzz** [comment]
@0x3333 Reverting this since it actually broke merges. See #17 

I can't reproduce #14, so I guess I merged this prematurely.

**Comment by 0x3333** [comment]
Are you sure about it? The PR is just to quote the file path, which is mandatory in case of paths with spaces. I'll take a look at it, but I'm using the version with the quotes and it is working, despite the version without it. I'll investigate the #17. Thanks!

**Comment by wubzz** [comment]
Yeah I was confused as well. I tried it locally after this PR and it threw the errors from #17. Presumably PDFtk for some reason considered the `"`'s to be part of the file name, which is weird.

**Comment by 0x3333** [comment]
For sure PDFtk is not the problem, it just receive the parameters, I believe that the problem is the distinction between windows vs others. I'll check this, couz the right thing to do is escape, but let me check it more deeply. I'll let you know my discoveries.

**Comment by timyhac** [comment]
Right now, this library uses shell-escape, but it doesn't handle windows OS correctly - https://github.com/xxorax/node-shell-escape/issues/9

**Comment by 0x3333** [comment]
In my case, I changed locally. But the PR caused some problems, I had no time to debug. But for sure, it is broken.

**Comment by wubzz** [comment]
Yeah I'm not sure why this caused problems tbh, can't quite remember. I've re-added this particular change and added a test for files with spaces in them.

FYI; Yes this library uses shell-escape, but it's never called when run on windows.

**Pull request merged**
